### ISSUE TITLE
Show snippets depending on variable value

### ISSUE THREAD

**Issue by junedev** [exercism/pr-commenter-action#20]
Would it be generally in scope for the tool to maybe in the future also support other ways than matching files to trigger a snippet?
E.g. we were thinking of showing a certain snippet when the PR title contains "typo".

We could set up a (template) variable "isTypoFix" in the workflow file. Then we would need some new key for the snippet instead of `files`, e.g.
```
  snippets:
    - id: some-id
      variable:
         value: {{ isTypoFix }}
         target: "true"  
      body: |
        Lorem ipsum ....
```

Maybe there is an easier way altogether implement something like this ...

Feel free to close the issue if this is out of scope.
